name: Test Bytes

on:
  pull_request:
    branches:
    - main

jobs:
  Test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Build
      run: |
        swift build --build-tests --enable-test-discovery
    - name: Run Tests
      run: |
        swift test --enable-test-discovery
